<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
@php $fmt = fn ($d) => $d ? \Illuminate\Support\Carbon::parse($d)->format('d M Y') : '—'; $cur = $ci->currency; $pi = $ci->proformaInvoice; $cust = $pi?->salesOrder?->customer; @endphp
<style>
  * { font-family: DejaVu Sans, sans-serif; }
  body { color:#1e293b; font-size:12px; margin:0; }
  .wrap { padding:26px 30px; }
  .head { display:flex; border-bottom:2px solid #ea580c; padding-bottom:12px; margin-bottom:16px; }
  .brand { font-size:20px; font-weight:bold; color:#ea580c; }
  .title { text-align:right; } .title .t { font-size:16px; font-weight:bold; letter-spacing:1px; }
  .num { font-family: DejaVu Sans Mono, monospace; font-size:13px; }
  table { width:100%; border-collapse:collapse; }
  .parties td { width:33%; vertical-align:top; padding:0 6px; }
  .box { border:1px solid #e2e8f0; padding:10px; border-radius:4px; }
  .lbl { font-size:10px; font-weight:bold; color:#64748b; text-transform:uppercase; letter-spacing:.5px; }
  .lines { margin-top:14px; } .lines th { background:#f1f5f9; text-align:left; padding:7px 8px; font-size:11px; border-bottom:1px solid #e2e8f0; }
  .lines td { padding:7px 8px; border-bottom:1px solid #eef2f7; } .r { text-align:right; } .tot td { font-weight:bold; }
  .foot { margin-top:22px; color:#94a3b8; font-size:10px; text-align:center; border-top:1px solid #e2e8f0; padding-top:10px; }
  .status { display:inline-block; padding:3px 12px; border-radius:12px; background:#ffedd5; color:#ea580c; font-weight:bold; font-size:11px; }
</style>
</head>
<body>
<div class="wrap">
  <div class="head">
    <div style="flex:1"><div class="brand">PharmaTrack</div><div style="font-size:11px;color:#64748b">Anti-Counterfeit &amp; Trade Platform</div></div>
    <div class="title"><div class="t">COMMERCIAL INVOICE</div><div class="num">{{ $ci->ci_number }}</div><div style="margin-top:4px"><span class="status">{{ $ci->status_label }}</span></div></div>
  </div>

  <table class="parties"><tr>
    <td><div class="box"><div class="lbl">Consignee</div><div style="font-weight:bold;margin-top:3px">{{ $cust?->name }}</div>
      <div style="font-size:11px;color:#475569">{{ $cust?->country?->name }}</div></div></td>
    <td><div class="box"><div class="lbl">Reference</div><div style="font-size:11px;margin-top:3px">PI: <span class="num">{{ $pi?->pi_number ?? '—' }}</span></div>
      <div style="font-size:11px">CI Date: {{ $fmt($ci->ci_date) }}</div><div style="font-size:11px">Incoterms: {{ $ci->incoterms ?: '—' }}</div></div></td>
    <td><div class="box"><div class="lbl">Customs</div><div style="font-size:11px;margin-top:3px">HS: {{ $ci->hs_code ?: '—' }}</div>
      <div style="font-size:11px">Origin: {{ $ci->country_of_origin ?: '—' }}</div>
      <div style="font-size:11px">POL: {{ $ci->port_of_loading ?: '—' }} → {{ $ci->port_of_discharge ?: '—' }}</div></div></td>
  </tr></table>

  <table class="lines">
    <thead><tr><th>#</th><th>Product</th><th>PRN</th><th>Batch</th><th class="r">Qty</th><th class="r">Unit Price</th><th class="r">Net kg</th><th class="r">Line Total</th></tr></thead>
    <tbody>
      @foreach($ci->lines as $i => $l)
        <tr><td>{{ $i + 1 }}</td><td>{{ $l->product?->name }}</td><td class="num">{{ $l->product?->prn }}</td><td>{{ $l->batch?->brn ?? '—' }}</td>
          <td class="r">{{ number_format($l->quantity) }}</td><td class="r">{{ $cur }} {{ number_format((float) $l->unit_price, 2) }}</td>
          <td class="r">{{ $l->net_weight_kg ? number_format((float) $l->net_weight_kg, 2) : '—' }}</td>
          <td class="r">{{ $cur }} {{ number_format((float) $l->line_total, 2) }}</td></tr>
      @endforeach
      <tr class="tot"><td colspan="7" class="r">Subtotal</td><td class="r">{{ $cur }} {{ number_format((float) $ci->subtotal, 2) }}</td></tr>
      <tr><td colspan="7" class="r">Freight</td><td class="r">{{ $cur }} {{ number_format((float) $ci->freight, 2) }}</td></tr>
      <tr><td colspan="7" class="r">Insurance</td><td class="r">{{ $cur }} {{ number_format((float) $ci->insurance, 2) }}</td></tr>
      <tr class="tot"><td colspan="7" class="r">Total Value</td><td class="r">{{ $cur }} {{ number_format((float) $ci->total_value, 2) }}</td></tr>
    </tbody>
  </table>

  @if($ci->bank_name)<div style="margin-top:12px"><div class="lbl">Beneficiary Bank</div><div style="font-size:11px">{{ $ci->bank_name }}@if($ci->bank_swift_code) · SWIFT: {{ $ci->bank_swift_code }}@endif · A/C: {{ $ci->bank_account_number ?: '—' }}</div></div>@endif
  @if($ci->remarks)<div style="margin-top:10px"><div class="lbl">Remarks</div><div style="font-size:11px">{{ $ci->remarks }}</div></div>@endif
  <div class="foot">Generated by PharmaTrack on {{ now()->format('d M Y, H:i') }} · {{ $ci->ci_number }}</div>
</div>
</body>
</html>
