<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
@php $fmt = fn ($d) => $d ? \Illuminate\Support\Carbon::parse($d)->format('d M Y') : '—'; $cur = $pi->currency; $so = $pi->salesOrder; $cust = $so?->customer; @endphp
<style>
  * { font-family: DejaVu Sans, sans-serif; }
  body { color:#1e293b; font-size:12px; margin:0; }
  .wrap { padding:26px 30px; }
  .head { display:flex; border-bottom:2px solid #7c3aed; padding-bottom:12px; margin-bottom:16px; }
  .brand { font-size:20px; font-weight:bold; color:#7c3aed; }
  .title { text-align:right; } .title .t { font-size:16px; font-weight:bold; letter-spacing:1px; }
  .num { font-family: DejaVu Sans Mono, monospace; font-size:13px; }
  table { width:100%; border-collapse:collapse; }
  .parties td { width:50%; vertical-align:top; padding:0 8px; }
  .box { border:1px solid #e2e8f0; padding:10px; border-radius:4px; }
  .lbl { font-size:10px; font-weight:bold; color:#64748b; text-transform:uppercase; letter-spacing:.5px; }
  .meta td { padding:4px 8px; }
  .lines { margin-top:14px; } .lines th { background:#f1f5f9; text-align:left; padding:7px 8px; font-size:11px; border-bottom:1px solid #e2e8f0; }
  .lines td { padding:7px 8px; border-bottom:1px solid #eef2f7; } .r { text-align:right; } .tot td { font-weight:bold; }
  .bank { margin-top:14px; border:1px solid #e2e8f0; border-radius:4px; padding:10px; background:#faf5ff; }
  .foot { margin-top:22px; color:#94a3b8; font-size:10px; text-align:center; border-top:1px solid #e2e8f0; padding-top:10px; }
  .status { display:inline-block; padding:3px 12px; border-radius:12px; background:#ede9fe; color:#7c3aed; font-weight:bold; font-size:11px; }
</style>
</head>
<body>
<div class="wrap">
  <div class="head">
    <div style="flex:1"><div class="brand">PharmaTrack</div><div style="font-size:11px;color:#64748b">Anti-Counterfeit &amp; Trade Platform</div></div>
    <div class="title"><div class="t">PROFORMA INVOICE</div><div class="num">{{ $pi->pi_number }}</div><div style="margin-top:4px"><span class="status">{{ $pi->status_label }}</span></div></div>
  </div>

  <table class="parties"><tr>
    <td><div class="box"><div class="lbl">Bill To</div><div style="font-weight:bold;margin-top:3px">{{ $cust?->name }}</div>
      <div style="font-size:11px;color:#475569">{{ $cust?->country?->name }}</div>
      <div style="font-size:11px;color:#475569">{{ $cust?->contact_person }}@if($cust?->contact_phone) · {{ $cust->contact_phone }}@endif</div></div></td>
    <td><div class="box"><div class="lbl">Reference</div>
      <div style="font-size:11px;margin-top:3px">SO: <span class="num">{{ $so?->so_number ?? '—' }}</span></div>
      <div style="font-size:11px">PI Date: {{ $fmt($pi->pi_date) }} · Valid: {{ $fmt($pi->valid_until) }}</div>
      <div style="font-size:11px">Incoterms: {{ $pi->incoterms ?: '—' }} · {{ $pi->payment_terms ?: '—' }}</div></div></td>
  </tr></table>

  <table class="lines">
    <thead><tr><th>#</th><th>Product</th><th>PRN</th><th>Batch</th><th class="r">Qty</th><th class="r">Unit Price</th><th class="r">Line Total</th></tr></thead>
    <tbody>
      @foreach($pi->lines as $i => $l)
        <tr><td>{{ $i + 1 }}</td><td>{{ $l->product?->name }}</td><td class="num">{{ $l->product?->prn }}</td><td>{{ $l->batch?->brn ?? '—' }}</td>
          <td class="r">{{ number_format($l->quantity) }}</td><td class="r">{{ $cur }} {{ number_format((float) $l->unit_price, 2) }}</td><td class="r">{{ $cur }} {{ number_format((float) $l->line_total, 2) }}</td></tr>
      @endforeach
      <tr class="tot"><td colspan="6" class="r">Subtotal</td><td class="r">{{ $cur }} {{ number_format((float) $pi->subtotal, 2) }}</td></tr>
      <tr><td colspan="6" class="r">Freight</td><td class="r">{{ $cur }} {{ number_format((float) $pi->freight, 2) }}</td></tr>
      <tr class="tot"><td colspan="6" class="r">Total Value</td><td class="r">{{ $cur }} {{ number_format((float) $pi->total_value, 2) }}</td></tr>
    </tbody>
  </table>

  @if($pi->bank_name || $pi->bank_swift_code)
    <div class="bank"><div class="lbl">Beneficiary Bank</div>
      <div style="font-size:11px;margin-top:3px">{{ $pi->bank_name }}@if($pi->bank_swift_code) · SWIFT: {{ $pi->bank_swift_code }}@endif</div>
      <div style="font-size:11px">A/C: {{ $pi->bank_account_number ?: '—' }}@if($pi->bank_iban) · IBAN: {{ $pi->bank_iban }}@endif</div>
    </div>
  @endif

  @if($pi->remarks)<div style="margin-top:12px"><div class="lbl">Remarks</div><div style="font-size:11px">{{ $pi->remarks }}</div></div>@endif
  <div class="foot">Generated by PharmaTrack on {{ now()->format('d M Y, H:i') }} · {{ $pi->pi_number }}</div>
</div>
</body>
</html>
