<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
@php $fmt = fn ($d) => $d ? \Illuminate\Support\Carbon::parse($d)->format('d M Y') : '—'; $cur = $so->currency; @endphp
<style>
  * { font-family: DejaVu Sans, sans-serif; }
  body { color:#1e293b; font-size:12px; margin:0; }
  .wrap { padding:26px 30px; }
  .head { display:flex; border-bottom:2px solid #059669; padding-bottom:12px; margin-bottom:16px; }
  .brand { font-size:20px; font-weight:bold; color:#059669; }
  .title { text-align:right; } .title .t { font-size:16px; font-weight:bold; letter-spacing:1px; }
  .num { font-family: DejaVu Sans Mono, monospace; font-size:13px; }
  table { width:100%; border-collapse:collapse; }
  .parties td { width:50%; vertical-align:top; padding:0 8px; }
  .box { border:1px solid #e2e8f0; padding:10px; border-radius:4px; }
  .lbl { font-size:10px; font-weight:bold; color:#64748b; text-transform:uppercase; letter-spacing:.5px; }
  .meta td { padding:4px 8px; }
  .lines { margin-top:14px; } .lines th { background:#f1f5f9; text-align:left; padding:7px 8px; font-size:11px; border-bottom:1px solid #e2e8f0; }
  .lines td { padding:7px 8px; border-bottom:1px solid #eef2f7; } .r { text-align:right; } .tot td { font-weight:bold; }
  .foot { margin-top:24px; color:#94a3b8; font-size:10px; text-align:center; border-top:1px solid #e2e8f0; padding-top:10px; }
  .status { display:inline-block; padding:3px 12px; border-radius:12px; background:#d1fae5; color:#059669; font-weight:bold; font-size:11px; }
</style>
</head>
<body>
<div class="wrap">
  <div class="head">
    <div style="flex:1"><div class="brand">PharmaTrack</div><div style="font-size:11px;color:#64748b">Anti-Counterfeit &amp; Trade Platform</div></div>
    <div class="title"><div class="t">SALES ORDER</div><div class="num">{{ $so->so_number }}</div><div style="margin-top:4px"><span class="status">{{ $so->status_label }}</span></div></div>
  </div>

  <table class="parties"><tr>
    <td><div class="box"><div class="lbl">Sold To</div><div style="font-weight:bold;margin-top:3px">{{ $so->customer?->name }}</div>
      <div style="font-size:11px;color:#475569">{{ $so->customer?->country?->name }}</div>
      <div style="font-size:11px;color:#475569">{{ $so->customer?->contact_person }}@if($so->customer?->contact_phone) · {{ $so->customer->contact_phone }}@endif</div></div></td>
    <td><div class="box"><div class="lbl">Reference</div><div style="font-size:11px;margin-top:3px">PO: <span class="num">{{ $so->purchaseOrder?->po_number ?? '—' }}</span></div>
      <div style="font-size:11px">SO Date: {{ $fmt($so->so_date) }}</div><div style="font-size:11px">Incoterms: {{ $so->incoterms ?: '—' }} · {{ $so->payment_terms ?: '—' }}</div></div></td>
  </tr></table>

  <table class="lines">
    <thead><tr><th>#</th><th>Product</th><th>PRN</th><th>Batch</th><th class="r">Qty</th><th class="r">Unit Price</th><th class="r">Line Total</th></tr></thead>
    <tbody>
      @foreach($so->lines as $i => $l)
        <tr><td>{{ $i + 1 }}</td><td>{{ $l->product?->name }}</td><td class="num">{{ $l->product?->prn }}</td><td>{{ $l->batch?->brn ?? '—' }}</td>
          <td class="r">{{ number_format($l->quantity) }}</td><td class="r">{{ $cur }} {{ number_format((float) $l->unit_price, 2) }}</td><td class="r">{{ $cur }} {{ number_format((float) $l->line_total, 2) }}</td></tr>
      @endforeach
      <tr class="tot"><td colspan="6" class="r">Total Value</td><td class="r">{{ $cur }} {{ number_format((float) $so->total_value, 2) }}</td></tr>
    </tbody>
  </table>

  @if($so->remarks)<div style="margin-top:14px"><div class="lbl">Remarks</div><div style="font-size:11px">{{ $so->remarks }}</div></div>@endif
  <div class="foot">Generated by PharmaTrack on {{ now()->format('d M Y, H:i') }} · {{ $so->so_number }}</div>
</div>
</body>
</html>
